# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Alexander S채채f
tagline:             'Software engineering student'
description:         'My personal page and blog. Based on Lanyon. Hosted on Github'
url:                 http://alexsaaf.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Alexander S채채f
  url:
  email:

# Custom vars
version:             1.0.0
